### ISSUE TITLE
Build Roadmap

### ISSUE THREAD

**Issue by barrosgg** [itidigitalbr/privacy-board-game#25]
Build a roadmap.
- [x] [Instructions & assignment](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/)
- [x] Start thinking about where you want to be in 12 weeks & how you'll get there.
- [x] You'll probably spend some time going over your goals and plan with your mentor next week.

**Comment by barrosgg** [comment]
# Roadmap
_**We're working with educators, designers and marketers to build the a board game to everyone that's use the web can learn how to navigate safely using good online security and privacy practices.**_

Privacy Board Game — Explore and analyze everyday situations on the Internet and learn how to navigate safely using good online security and privacy practices. This game is proudly part of [Offline Games Challenge](https://github.com/MozillaFoundation/mpa-offline-games-challenge) from Mozilla Foundation.

## What do we need to do?

This issue is our roadmap. It's a place to start to investigate the myriad of issues that you can contribute to. Check out the different [milestones](https://github.com/itidigitalbr/privacy-board-game/milestones) listed below, but feel free to explore the [issues by label](https://github.com/itidigitalbr/privacy-board-game/labels) too.

Please check out our [code of conduct](https://github.com/itidigitalbr/privacy-board-game/blob/master/CODE_OF_CONDUCT.md) to help you get started, and the [README](https://github.com/itidigitalbr/privacy-board-game/blob/master/README.md) for an overview if you haven't read it yet!

### Milestone: [Community](https://github.com/itidigitalbr/privacy-board-game/milestone/6)
>  Recruit and onboarding new contributors in the project

**Tasks**
- #39  
- #40 

_Due by September 30, 2017_
### Milestone: [Design board game](https://github.com/itidigitalbr/privacy-board-game/milestone/1)
>  The key to our mission here is to develop the game, this milestone ensure that all the tasks are well grouped and easy to track.

**Tasks**
- #27 
- #28 
- #29 

_Due by October 14, 2017_
### Milestone: [Mozilla Festival 2017](https://github.com/itidigitalbr/privacy-board-game/milestone/2)
> After developing our first prototype we will demonstrate our game in a fun session of the Mozilla Festival.

**Tasks**
- #37 
- #38 
_Due by October 14, 2017_
### Milestone: [Teaching kit](https://github.com/itidigitalbr/privacy-board-game/milestone/3)
>  Educators will be the key to ensuring that more people play our game, we'll make sure they have all the resources, tips and lesson plans easy for a session.

**Tasks**
- #34 
- #35 
- #36

_Due by October 28, 2017_
### Milestone: [Website development](https://github.com/itidigitalbr/privacy-board-game/milestone/4)
>  We will create a simple website to bring all our resources together in an good interface for potential players or facilitators. This will be the key to help us on social media campaigns.

**Tasks**
- #19 
- #20 
- #21 
- #22 
- #23 

_Due by November 11, 2017_
### Milestone: [Relations](https://github.com/itidigitalbr/privacy-board-game/milestone/7)
> Relationship and partnerships with potential users/members

**Tasks**
- #31 
- #32 
- #33 

_Due by November 25, 2017_
### Milestone: [Social media campaign](https://github.com/itidigitalbr/privacy-board-game/milestone/5)
>  In addition to developing our game and creating awesome resources to keep learning moving forward, we need to inform, spread, speak and promote our game. This social media campaign will ensure this.

**Tasks**
- #31 
- #32 
- #33 

_Due by November 25, 2017_

**Comment by barrosgg** [comment]
My Open Canvas (https://goo.gl/DXpmNY) and Roadmap (https://goo.gl/waQinQ).
